
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFinal.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Artista
{

    public long Id { get; set; }

    public string NombreArtista { get; set; }

    public string DescripcionArtista { get; set; }

    public long Companiaid { get; set; }



    public virtual Compania Compania { get; set; }

}

}
