
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFinal.DataLayer
{

    using System;
    using System.Collections.Generic;

    public partial class Compra
    {

        public long Id { get; set; }

        public string MetodoDePago { get; set; }

        public int Unidades { get; set; }

        public int Descuento { get; set; }

        public long LocalidadEspectaculoid { get; set; }

        public long Espectaculoid { get; set; }

        public System.DateTime FechaHora { get; set; }

        public Nullable<long> Cuentaid { get; set; }



        public virtual Espectaculo Espectaculo { get; set; }

        public virtual LocalidadEspectaculo LocalidadEspectaculo { get; set; }

        public virtual Cuenta Cuenta { get; set; }

    }

}
