
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFinal.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Empleado
{

    public long Id { get; set; }

    public long Personaid { get; set; }

    public long Cuentaid { get; set; }



    public virtual Cuenta Cuenta { get; set; }

    public virtual Persona Persona { get; set; }

}

}
