
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFinal.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Espectaculo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Espectaculo()
    {

        this.Compra = new HashSet<Compra>();

        this.LocalidadEspectaculo = new HashSet<LocalidadEspectaculo>();

    }


    public long Id { get; set; }

    public string NombreEspectaculo { get; set; }

    public string DescripcionEspectaculo { get; set; }

    public Nullable<System.DateTime> FechaYHora { get; set; }

    public bool EstadoEspectaculo { get; set; }

    public Nullable<int> PrecioEspectaculo { get; set; }

    public long Companiaid { get; set; }



    public virtual Compania Compania { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Compra> Compra { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LocalidadEspectaculo> LocalidadEspectaculo { get; set; }

}

}
