
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFinal.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class LocalidadAsiento
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LocalidadAsiento()
    {

        this.LocalidadEspectaculo = new HashSet<LocalidadEspectaculo>();

    }


    public long Id { get; set; }

    public int NumeroAsiento { get; set; }

    public string Entrada { get; set; }

    public bool EstadoAsiento { get; set; }

    public long Sectorid { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LocalidadEspectaculo> LocalidadEspectaculo { get; set; }

    public virtual Sector Sector { get; set; }

}

}
