

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFinal.DataLayer
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TeatroEntities : DbContext
{
    public TeatroEntities()
        : base("name=TeatroEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Artista> Artista { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Compania> Compania { get; set; }

    public virtual DbSet<Compra> Compra { get; set; }

    public virtual DbSet<Cuenta> Cuenta { get; set; }

    public virtual DbSet<Empleado> Empleado { get; set; }

    public virtual DbSet<Espectaculo> Espectaculo { get; set; }

    public virtual DbSet<LocalidadAsiento> LocalidadAsiento { get; set; }

    public virtual DbSet<LocalidadEspectaculo> LocalidadEspectaculo { get; set; }

    public virtual DbSet<Persona> Persona { get; set; }

    public virtual DbSet<Sector> Sector { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

}

}

