
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFinal.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Sector
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sector()
    {

        this.LocalidadAsiento = new HashSet<LocalidadAsiento>();

        this.LocalidadEspectaculo = new HashSet<LocalidadEspectaculo>();

    }


    public long Id { get; set; }

    public string NombreSector { get; set; }

    public int Cupon { get; set; }

    public Nullable<int> PrecioSector { get; set; }

    public bool EstadoSector { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LocalidadAsiento> LocalidadAsiento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LocalidadEspectaculo> LocalidadEspectaculo { get; set; }

}

}
